packages:
  - .

allowBuilds:
  esbuild: set this to true or false
  fallow: set this to true or false

pnpm:
  autoInstallPeers: true
  strictPeerDependencies: false
  allowBuilds:
    esbuild: true
    fallow: true
  packageImportMethod: clone-or-copy
