// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from "@/hooks/use-toast";

// Get configuration from environment variables (build time)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://gsvyxsddmddipeoduyys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Create Supabase client with environment configuration
export const createSupabaseClient = async () => {
  try {
    console.log("[SupabaseClient] Initializing Supabase client...");
    
    if (!SUPABASE_PUBLISHABLE_KEY) {
      console.error("[SupabaseClient] No Supabase anon key found in environment variables.");
      throw new Error("Failed to initialize Supabase client: No authentication key configured.");
    }
    
    console.log("[SupabaseClient] Creating Supabase client with URL:", SUPABASE_URL);
    
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        storage: localStorage,
        storageKey: 'aafairshare-auth',
        detectSessionInUrl: true,
        flowType: 'pkce'
      },
      global: {
        headers: {
          'Content-Type': 'application/json',
        },
        fetch: (url, options) => {
          return fetch(url, {
            ...options,
            signal: options?.signal || AbortSignal.timeout(30000)
          }).catch(error => {
            console.error("Fetch error:", error);
            throw error;
          });
        }
      },
      realtime: {
        heartbeatIntervalMs: 30000
      }
    });
  } catch (error) {
    console.error("[SupabaseClient] Error initializing Supabase client:", error);
    // Only show toast if this is not during initial page load
    if (document.readyState === 'complete') {
      toast({
        title: "Connection Error",
        description: (error instanceof Error && error.message) ? error.message : "Failed to initialize database connection. Please try again later.",
        variant: "destructive"
      });
    }
    throw error;
  }
};

// Initialize client promise immediately to handle OAuth callbacks
console.log("[SupabaseClient] Starting client initialization...");
let supabaseClientPromise: Promise<ReturnType<typeof createClient<Database>>> = createSupabaseClient();
let supabaseClientInstance: ReturnType<typeof createClient<Database>> | null = null;

// Store the instance once initialized
supabaseClientPromise.then(client => {
  supabaseClientInstance = client;
  console.log("[SupabaseClient] Client instance ready for synchronous access");
}).catch(error => {
  console.error("[SupabaseClient] Failed to initialize client:", error);
});

// Get Supabase client - returns the promise that resolves to the client
export const getSupabase = async () => {
  return supabaseClientPromise;
};

// Synchronous client getter for contexts where async is not possible
// This will return null until the client is initialized
export const getSupabaseSync = (): ReturnType<typeof createClient<Database>> | null => {
  return supabaseClientInstance;
};

// For backward compatibility - use the async client
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get: (target, prop) => {
    if (!supabaseClientInstance) {
      console.warn('[SupabaseClient] Attempted to use supabase client before initialization. Client may not be ready yet.');
      // Return a function that throws to avoid silent failures
      if (typeof prop === 'string' && prop !== 'then') {
        throw new Error('Supabase client not initialized yet. Use await getSupabase() instead.');
      }
      return undefined;
    }
    return (supabaseClientInstance as any)[prop];
  }
});

// Helper to check network connection
export const isOnline = () => typeof navigator !== 'undefined' && navigator.onLine;

// Clean up auth state utility - export directly from the client file
export const cleanupAuthState = (): void => {
  console.log("Cleaning up auth state");
  
  // Remove standard auth tokens
  localStorage.removeItem('supabase.auth.token');
  
  // Remove all Supabase auth keys from localStorage
  Object.keys(localStorage).forEach((key) => {
    if (key.startsWith('supabase.auth.') || key.includes('sb-') || key.includes('aafairshare-auth')) {
      console.log(`Removing localStorage item: ${key}`);
      localStorage.removeItem(key);
    }
  });
  
  // Do the same for sessionStorage
  try {
    if (typeof sessionStorage !== 'undefined') {
      Object.keys(sessionStorage).forEach((key) => {
        if (key.startsWith('supabase.auth.') || key.includes('sb-') || key.includes('aafairshare-auth')) {
          console.log(`Removing sessionStorage item: ${key}`);
          sessionStorage.removeItem(key);
        }
      });
    }
  } catch (e) {
    console.error("Error cleaning sessionStorage:", e);
  }
  
  // Also remove project-specific error markers
  localStorage.removeItem('auth-error-detected');
};

// Function to try force signout (ignores errors)
export const forceSignOut = async (): Promise<void> => {
  try {
    const client = await getSupabase();
    await client.auth.signOut({ scope: 'global' });
    console.log("Successfully signed out from Supabase");
  } catch (err) {
    console.error("Error during signOut:", err);
    // Continue even if this fails
  }
};

// Export checkSupabaseConnection from services to avoid duplication
export { checkSupabaseConnection } from '@/services/api/auth/authUtilities';
