
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { showToast } from '@/components/ui/use-toast';

// Default to empty strings - will be populated by the edge function
let SUPABASE_URL = "";
let SUPABASE_PUBLISHABLE_KEY = "";

// Create Supabase client with dynamic configuration
export const createSupabaseClient = async () => {
  try {
    // Fetch configuration from edge function
    const response = await fetch('https://gsvyxsddmddipeoduyys.supabase.co/functions/v1/get-config');
    
    if (!response.ok) {
      throw new Error(`Failed to fetch config: ${response.statusText}`);
    }
    
    const config = await response.json();
    SUPABASE_URL = config.supabaseUrl;
    SUPABASE_PUBLISHABLE_KEY = config.supabaseAnonKey;
    
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        storage: localStorage,
        storageKey: 'aafairshare-auth',
        detectSessionInUrl: false,
        flowType: 'implicit'
      },
      global: {
        headers: {
          'Content-Type': 'application/json',
        },
        fetch: (url, options) => {
          return fetch(url, {
            ...options,
            signal: options?.signal || AbortSignal.timeout(30000)
          }).catch(error => {
            console.error("Fetch error:", error);
            throw error;
          });
        }
      },
      realtime: {
        heartbeatIntervalMs: 30000
      }
    });
  } catch (error) {
    console.error("Error initializing Supabase client:", error);
    showToast({
      title: "Connection Error",
      description: "Failed to initialize database connection. Please try again later.",
      variant: "destructive"
    });
    throw error;
  }
};

// Initialize client
let supabaseClientPromise: Promise<ReturnType<typeof createSupabaseClient>>;

// Lazy-loaded Supabase client - only initialize when first needed
export const getSupabase = async () => {
  if (!supabaseClientPromise) {
    supabaseClientPromise = createSupabaseClient();
  }
  return supabaseClientPromise;
};

// Helper to check network connection
export const isOnline = () => typeof navigator !== 'undefined' && navigator.onLine;

// Clean up auth state utility - export directly from the client file
export const cleanupAuthState = (): void => {
  console.log("Cleaning up auth state");
  
  // Remove standard auth tokens
  localStorage.removeItem('supabase.auth.token');
  
  // Remove all Supabase auth keys from localStorage
  Object.keys(localStorage).forEach((key) => {
    if (key.startsWith('supabase.auth.') || key.includes('sb-') || key.includes('aafairshare-auth')) {
      console.log(`Removing localStorage item: ${key}`);
      localStorage.removeItem(key);
    }
  });
  
  // Do the same for sessionStorage
  try {
    if (typeof sessionStorage !== 'undefined') {
      Object.keys(sessionStorage).forEach((key) => {
        if (key.startsWith('supabase.auth.') || key.includes('sb-') || key.includes('aafairshare-auth')) {
          console.log(`Removing sessionStorage item: ${key}`);
          sessionStorage.removeItem(key);
        }
      });
    }
  } catch (e) {
    console.error("Error cleaning sessionStorage:", e);
  }
  
  // Also remove project-specific error markers
  localStorage.removeItem('auth-error-detected');
};

// Function to check Supabase availability with retry
export const checkSupabaseConnection = async (retries = 2): Promise<boolean> => {
  let attempt = 0;
  
  while (attempt <= retries) {
    try {
      // Simple check with getSession to verify if we can connect to Supabase
      const { data, error } = await supabase.auth.getSession();
      
      // If we can reach Supabase, consider it a successful connection
      return !error;
    } catch (e) {
      console.error(`Error checking Supabase connection (attempt ${attempt + 1}):`, e);
      attempt++;
      
      // Only wait between retries, not after the last one
      if (attempt <= retries) {
        await new Promise(resolve => setTimeout(resolve, 1500 * attempt));
      }
    }
  }
  
  return false;
};

// Function to try force signout (ignores errors)
export const forceSignOut = async (): Promise<void> => {
  try {
    await supabase.auth.signOut({ scope: 'global' });
    console.log("Successfully signed out from Supabase");
  } catch (err) {
    console.error("Error during signOut:", err);
    // Continue even if this fails
  }
};
